/**
 * The optimizer's **policy** knobs — the numbers that encode what we are willing to recommend, as
 * opposed to what the rules permit (`rules.ts`, read from `scoring_config`) or what the data says
 * (`projections/fitted.ts`, regenerated by `pnpm fit:model`).
 *
 * They live in their own file for the reason `fitted.ts` gives for its own: a number that steers a
 * recommendation has to be reviewable in a diff. The difference is provenance — nothing here is
 * fitted, and each value says so. A knob that is measured later moves to `fitted.ts` and stops being
 * a policy at all.
 *
 * Plan `009-recommendation-guards.md` asked for "config, not a constant, the same place the other
 * policy knobs live". There was no such place: the optimizer's knobs were module constants in
 * `optimizer.service.ts`. This file is it.
 */

/**
 * Minimum Premier League appearances before a player may enter the optimizer's candidate pool
 * (B-010). An appearance is a gameweek row with `minutes > 0`, counted over the stored archive plus
 * the current season.
 *
 * **Unfitted — a deliberate refusal, not a measurement.** A player with one match of history has a
 * per-90 rate estimated from that one match, shrunk toward a positional mean; shrinkage bounds the
 * error, it does not remove it, and the optimizer is a maximiser, so it hunts exactly the players
 * whose estimate is most inflated by noise. 11 is ">10", the threshold measured feasible on
 * 2026-08-26: 227 of 614 players excluded, priciest excluded £6.5m, cheapest legal eligible 15
 * £65.5m.
 *
 * This filters the POOL only. Every player keeps a projection row, so a user squad holding a new
 * signing still scores.
 */
export const MIN_APPEARANCES = 11;

/**
 * Horizon points charged per conflicting (attacker, defender) pair held at once (B-011) — one of our
 * attackers against one of our defenders in the same fixture of the first horizon gameweek.
 *
 * **A policy choice, and measured NOT to be an improvement** (`reports/guards-009.md`, 2026-08-27).
 * The two picks bet on opposite outcomes of one match, so owning both buys correlation the linear
 * objective cannot see. The lambda sweep over 103 archived gameweeks was supposed to earn this
 * number and did not: the pooled gain at lambda 1 is +0.59 +/- 0.92 realised points per gameweek —
 * inside its own noise — the per-season sign flips (-2.41 in 2023-24, +2.34 in 2024-25), and the
 * downside the rule was argued for as insurance got WORSE, worst decile 32.0 to 30.0. The sweep also
 * showed the knob is close to binary: every value from 0.5 to 4 lands within 0.13 points of the
 * others, so there is no interior optimum to tune toward.
 *
 * It stays on at 1.0 because a squad that bets on a clean sheet and against it at the same time is
 * not one we want to defend to a user — not because it scores more points. Anyone raising or
 * lowering this is making a policy argument, not a measured one, and should say so.
 *
 * A penalty rather than an exclusion, by maintainer decision 2026-08-26: the solver may still take
 * the pair when it is worth more than this.
 */
export const COLLISION_LAMBDA = 1.0;

/**
 * Attacker = FWD + MID, defensive = DEF + GKP (maintainer decision 2026-08-26). FWD-only would have
 * missed the measured case — Palmer, the captain colliding with two of our own Brighton defenders,
 * is a MID.
 */
export const ATTACKING_POSITIONS = ['FWD', 'MID'] as const;
export const DEFENSIVE_POSITIONS = ['DEF', 'GKP'] as const;
