/**
 * The optimizer's **policy** knobs — the numbers that encode what we are willing to recommend, as
 * opposed to what the rules permit (`rules.ts`, read from `scoring_config`) or what the data says
 * (`projections/fitted.ts`, regenerated by `pnpm fit:model`).
 *
 * They live in their own file for the reason `fitted.ts` gives for its own: a number that steers a
 * recommendation has to be reviewable in a diff. The difference is provenance — nothing here is
 * fitted, and each value says so. A knob that is measured later moves to `fitted.ts` and stops being
 * a policy at all.
 *
 * Plan `009-recommendation-guards.md` asked for "config, not a constant, the same place the other
 * policy knobs live". There was no such place: the optimizer's knobs were module constants in
 * `optimizer.service.ts`. This file is it.
 */

/**
 * Minimum Premier League appearances before a player may enter the optimizer's candidate pool
 * (B-010). An appearance is a gameweek row with `minutes > 0`, counted over the stored archive plus
 * the current season.
 *
 * **Unfitted — a deliberate refusal, not a measurement.** A player with one match of history has a
 * per-90 rate estimated from that one match, shrunk toward a positional mean; shrinkage bounds the
 * error, it does not remove it, and the optimizer is a maximiser, so it hunts exactly the players
 * whose estimate is most inflated by noise. 11 is ">10", the threshold measured feasible on
 * 2026-08-26: 227 of 614 players excluded, priciest excluded £6.5m, cheapest legal eligible 15
 * £65.5m.
 *
 * This filters the POOL only. Every player keeps a projection row, so a user squad holding a new
 * signing still scores.
 */
export const MIN_APPEARANCES = 11;

/**
 * Horizon points charged per conflicting (attacker, defender) pair the squad HOLDS (B-011, restored
 * to ownership by B-025) — one of our attackers against one of our defenders in the same fixture of
 * the first horizon gameweek.
 *
 * **A policy choice, and measured NOT to be an improvement** (`reports/guards-009.md`, 2026-08-27).
 * The two picks bet on opposite outcomes of one match, so owning both buys correlation the linear
 * objective cannot see. The lambda sweep over 103 archived gameweeks was supposed to earn this
 * number and did not: the pooled gain at lambda 1 is +0.59 +/- 0.92 realised points per gameweek —
 * inside its own noise — the per-season sign flips (-2.41 in 2023-24, +2.34 in 2024-25), and the
 * downside the rule was argued for as insurance got WORSE, worst decile 32.0 to 30.0. The sweep also
 * showed the knob is close to binary: every value from 0.5 to 4 lands within 0.13 points of the
 * others, so there is no interior optimum to tune toward.
 *
 * It stays on at 1.0 because a squad that bets on a clean sheet and against it at the same time is
 * not one we want to defend to a user — not because it scores more points. Anyone raising or
 * lowering this is making a policy argument, not a measured one, and should say so.
 *
 * A penalty rather than an exclusion, by maintainer decision 2026-08-26: the solver may still take
 * the pair when it is worth more than this.
 *
 * **It is charged against `x`, and B-025 put it back there after B-023 moved it to `y`.** Charging
 * the XI let the solver satisfy the rule by BENCHING one side while still paying for both — measured
 * on the live GW2 solve, 3.30 horizon points given up in the eleven while £9.6m sat on two players it
 * refused to start, and measured again over an archived season by `pnpm replay:xi`: a conflicting
 * pair owned in all 38 rounds and both sides started in 8, at a cost of 78.56 projected points.
 * B-011's own sentence is about *holding* both sides, so that is where the charge belongs. Once a
 * pair is owned the eleven is chosen on points alone, which means a squad that pays for the pair
 * also starts it if the projections say so — that is the intended behaviour, not a regression.
 */
export const COLLISION_LAMBDA = 1.0;

/**
 * **Charged raw, and NOT scaled by the bench weight (B-026).**
 *
 * B-025 shipped it scaled — `benchWeight × λ` = 0.7 — reasoning that B-023 changed what a squad place
 * is worth, so the constant had to be re-scaled to keep the weight B-011 measured. Half of that is
 * right and it is the half that does not matter. After B-023 a player's coefficients depend on
 * whether he starts: a BENCHED owned player carries `benchWeight · ep`, so a raw λ is 1/benchWeight
 * = 1.43x the measured strength for him — but a STARTER carries
 * `benchWeight · ep + (1 − benchWeight) · ep = ep`, exactly the pre-B-023 weight, so a raw λ was
 * already right for him and the scaling UNDER-charged him by 30%. A colliding pair is usually two
 * startable players.
 *
 * Neither is measurable: the sweep put every λ from 0.5 to 4 within 0.13 realised points. The reason
 * to stop scaling is not the arithmetic but the coupling — two knobs that move together need a
 * harness that can see both, and the one that can see the XI at all (`pnpm replay:xi`) is one season
 * old. A constant that means what its comment says is worth more than a scaled one that means it for
 * a player nobody starts.
 *
 * `transfer-lp.ts` therefore charges the same number for the first time since B-023, which is a
 * coincidence rather than a rule: its coefficient on `x` is the full `ep`. If the XI and captain
 * families ever land there (B-024), that stays true and nothing needs to change with them.
 */

/**
 * Attacker = FWD + MID, defensive = DEF + GKP (maintainer decision 2026-08-26). FWD-only would have
 * missed the measured case — Palmer, the captain colliding with two of our own Brighton defenders,
 * is a MID.
 */
export const ATTACKING_POSITIONS = ['FWD', 'MID'] as const;
export const DEFENSIVE_POSITIONS = ['DEF', 'GKP'] as const;

/**
 * What a bench place is worth, as a fraction of a starting place (B-023).
 *
 * **1.0, and it was measured rather than assumed — including the part that says the discount does
 * not work.** `fpl-optimizer` estimates ~0.1, B-023 proposed shipping that, and the entry's own first
 * trap warned that doing so unmeasured would trade one arbitrary weight for another. It would have.
 *
 * `pnpm optimize:bench-sweep` walks a full archived season per weight through the same simulator
 * `pnpm decision-quality` uses. The `no-transfer` column is the one that isolates the opening squad,
 * and it is not flat:
 *
 * | weight | 0 | 0.1 | 0.2 | 0.35 | 0.5 | 0.7 | 0.85 | 1.0 |
 * |---|---:|---:|---:|---:|---:|---:|---:|---:|
 * | no-transfer | 1457 | 1457 | 1329 | 1299 | 1299 | **1635** | **1635** | **1635** |
 * | greedy-1ft | 1881 | 1881 | 1893 | 1867 | 1867 | 1881 | 1881 | 1881 |
 *
 * Every value at or below 0.5 costs **~180 points of season**, and 0.7 through 1.0 cannot be told
 * apart. So the season evidence rules out the low end and says nothing inside the top plateau.
 *
 * **0.7 rather than 1.0, and the tie is broken by the objective being well posed rather than by
 * taste.** The XI coefficient is `1 − benchWeight`. At exactly 1.0 it is **zero**, and the starting
 * eleven stops being determined by anything but the collision penalty — the solver becomes free to
 * bench a 17.2 defender for a 15.2 one, because within a chosen fifteen it no longer cares who
 * plays. Confirmed on the live GW2 solve at 1.0: Wieffer (17.22) and De Cuyper (16.34) were benched
 * behind Canvot (15.23) and Ballard (15.20), which is not a recommendation anybody should read.
 *
 * The season sweep could not see that, because the simulator re-chooses its lineup every round from
 * realised availability and never reads the LP's XI. A measurement that does not look at the thing
 * you are about to serve is not a licence to ship it.
 *
 * **What 0.7 did NOT fix, and what B-025 did about it.** On the live GW2 solve the collision rule
 * expressed itself by BENCHING the two Brighton defenders behind cheaper ones rather than by moving
 * the armband off Palmer — Wieffer 17.22 and De Cuyper 16.34 sat, Ballard 15.20 and Lacroix 15.06
 * started. This comment used to call that "B-011 working, not failing", on the arithmetic that
 * benching the pair costs `(1 − 0.7) × 3.30 = 0.99` of objective and saves 4 penalty points. The
 * arithmetic was right and the reading was wrong: B-011's rule is about *holding* both sides, and a
 * squad that pays £9.6m for two players it refuses to start has not obeyed it, it has evaded it.
 * B-025 moved the charge back onto `x`, where benching cannot answer it. The XI is now chosen on
 * points alone, so this bench weight no longer interacts with the collision penalty at all — which
 * is the other half of what B-025 fixed, because the two knobs were coupled and only one harness
 * could see either.
 *
 * **Why a heavily discounted bench loses points, which is the interesting half.** A bench bought as
 * fodder cannot cover a blank. An auto-substitution only fires for a player who did not play, and if
 * the substitute did not play either the manager keeps the zero. Over a season held without
 * transfers, that costs more than the money saved buys. The `greedy-1ft` row is flat because
 * transfers repair a weak bench over time — so the effect is real and it is largest exactly where a
 * manager has fewest moves.
 *
 * **This does NOT put the objective back where it was.** `ilp.ts` still emits the XI and captain
 * variables the spec asks for, and the captain's double — absent from the objective entirely before
 * B-023 — is in it. At weight 1.0 the bench term simply contributes nothing, which is the measured
 * answer rather than the original oversight.
 */
export const BENCH_WEIGHT = 0.7;
