/**
 * The optimizer's **policy** knobs — the numbers that encode what we are willing to recommend, as
 * opposed to what the rules permit (`rules.ts`, read from `scoring_config`) or what the data says
 * (`projections/fitted.ts`, regenerated by `pnpm fit:model`).
 *
 * They live in their own file for the reason `fitted.ts` gives for its own: a number that steers a
 * recommendation has to be reviewable in a diff. The difference is provenance — nothing here is
 * fitted, and each value says so. A knob that is measured later moves to `fitted.ts` and stops being
 * a policy at all.
 *
 * Plan `009-recommendation-guards.md` asked for "config, not a constant, the same place the other
 * policy knobs live". There was no such place: the optimizer's knobs were module constants in
 * `optimizer.service.ts`. This file is it.
 */

/**
 * Minimum Premier League appearances before a player may enter the optimizer's candidate pool
 * (B-010). An appearance is a gameweek row with `minutes > 0`, counted over the stored archive plus
 * the current season.
 *
 * **Unfitted — a deliberate refusal, not a measurement.** A player with one match of history has a
 * per-90 rate estimated from that one match, shrunk toward a positional mean; shrinkage bounds the
 * error, it does not remove it, and the optimizer is a maximiser, so it hunts exactly the players
 * whose estimate is most inflated by noise. 11 is ">10", the threshold measured feasible on
 * 2026-08-26: 227 of 614 players excluded, priciest excluded £6.5m, cheapest legal eligible 15
 * £65.5m.
 *
 * This filters the POOL only. Every player keeps a projection row, so a user squad holding a new
 * signing still scores.
 */
export const MIN_APPEARANCES = 11;

/**
 * Horizon points charged per pair of our own defensive players who START for the same club (B-029).
 *
 * **What this replaced, and why that one went.** B-011 charged a squad for owning one of our attackers
 * against one of our defensive players in the same match — "a squad that bets against itself". B-028
 * measured that over 101,103 pairs and three archived seasons and it did not survive:
 *
 *  - the effect is real. Correlation −0.195 ± 0.003, stable per season, and a defensive player takes
 *    1.48 points in matches where the attacker facing him returned against 3.04 where he blanked;
 *  - but it is a HEDGE. `Var(A + D) = Var(A) + Var(D) + 2·Cov(A, D)`, the covariance is negative, and
 *    holding both sides cut the pair's variance by 19.5%. Expectation is linear, so no correlation can
 *    make the objective wrong in the mean. The rule priced insurance, which is why its own lambda
 *    sweep found +0.59 ± 0.92 realised points over 103 gameweeks and no benefit;
 *  - and it missed the bigger term. Two defensive players of one club covary **+5.58** against −4.15
 *    for both collision terms together. Given a squad already holding two defenders of a club, adding
 *    the attacker who faces them costs 0.65 points² of variance against 8.96 for an uncorrelated
 *    attacker — he was the safest addition available and B-011 charged extra for him.
 *
 * So the charge points at the concentration instead: two of ours in the same defence, taking the field
 * together, sharing one clean sheet.
 *
 * **Keyed to the XI, and the contrast with B-011 is the whole lesson.** B-011's charge belonged on
 * ownership because the bet was *buying* both sides — benching one changed nothing about having paid
 * for him, which is exactly how B-023's version got dodged. Concentration is not that: a benched
 * player scores nothing and carries no variance, so benching genuinely removes the exposure and is a
 * legitimate answer to this charge. Charge what you want to refuse, and key it to the decision you
 * want to change.
 *
 * **1.0 is a POLICY number and nothing here has measured it.** B-028 established that the covariance
 * exists and which way it points. It did not establish that a lower-variance squad scores more, and it
 * cannot: that depends on whether the objective is expected points or expected rank, and this project
 * optimises expected points. Anyone moving this number is making a policy argument, should say so, and
 * now has `pnpm replay:xi` — a harness that can actually see which eleven the solver picked — to
 * measure it on.
 */
export const DEFENCE_CONCENTRATION_LAMBDA = 1.0;

/**
 * Defensive = DEF + GKP. A keeper and his defenders share ONE clean sheet, exactly, which is what
 * makes them the concentrated holding B-029 charges for.
 *
 * `ATTACKING_POSITIONS` used to sit beside this, for B-011's attacker-against-defender pairing. It
 * went with the rule (B-029) rather than being left inert for a future reader to wire back up.
 */
export const DEFENSIVE_POSITIONS = ['DEF', 'GKP'] as const;

/**
 * What a bench place is worth, as a fraction of a starting place (B-023).
 *
 * **1.0, and it was measured rather than assumed — including the part that says the discount does
 * not work.** `fpl-optimizer` estimates ~0.1, B-023 proposed shipping that, and the entry's own first
 * trap warned that doing so unmeasured would trade one arbitrary weight for another. It would have.
 *
 * `pnpm optimize:bench-sweep` walks a full archived season per weight through the same simulator
 * `pnpm decision-quality` uses. The `no-transfer` column is the one that isolates the opening squad,
 * and it is not flat:
 *
 * | weight | 0 | 0.1 | 0.2 | 0.35 | 0.5 | 0.7 | 0.85 | 1.0 |
 * |---|---:|---:|---:|---:|---:|---:|---:|---:|
 * | no-transfer | 1457 | 1457 | 1329 | 1299 | 1299 | **1635** | **1635** | **1635** |
 * | greedy-1ft | 1881 | 1881 | 1893 | 1867 | 1867 | 1881 | 1881 | 1881 |
 *
 * Every value at or below 0.5 costs **~180 points of season**, and 0.7 through 1.0 cannot be told
 * apart. So the season evidence rules out the low end and says nothing inside the top plateau.
 *
 * **0.7 rather than 1.0, and the tie is broken by the objective being well posed rather than by
 * taste.** The XI coefficient is `1 − benchWeight`. At exactly 1.0 it is **zero**, and the starting
 * eleven stops being determined by anything but the collision penalty — the solver becomes free to
 * bench a 17.2 defender for a 15.2 one, because within a chosen fifteen it no longer cares who
 * plays. Confirmed on the live GW2 solve at 1.0: Wieffer (17.22) and De Cuyper (16.34) were benched
 * behind Canvot (15.23) and Ballard (15.20), which is not a recommendation anybody should read.
 *
 * The season sweep could not see that, because the simulator re-chooses its lineup every round from
 * realised availability and never reads the LP's XI. A measurement that does not look at the thing
 * you are about to serve is not a licence to ship it.
 *
 * **What 0.7 did NOT fix, and what B-025 did about it.** On the live GW2 solve the collision rule
 * expressed itself by BENCHING the two Brighton defenders behind cheaper ones rather than by moving
 * the armband off Palmer — Wieffer 17.22 and De Cuyper 16.34 sat, Ballard 15.20 and Lacroix 15.06
 * started. This comment used to call that "B-011 working, not failing", on the arithmetic that
 * benching the pair costs `(1 − 0.7) × 3.30 = 0.99` of objective and saves 4 penalty points. The
 * arithmetic was right and the reading was wrong: B-011's rule is about *holding* both sides, and a
 * squad that pays £9.6m for two players it refuses to start has not obeyed it, it has evaded it.
 * B-025 moved the charge back onto `x`, where benching cannot answer it. The XI is now chosen on
 * points alone, so this bench weight no longer interacts with the collision penalty at all — which
 * is the other half of what B-025 fixed, because the two knobs were coupled and only one harness
 * could see either.
 *
 * **Why a heavily discounted bench loses points, which is the interesting half.** A bench bought as
 * fodder cannot cover a blank. An auto-substitution only fires for a player who did not play, and if
 * the substitute did not play either the manager keeps the zero. Over a season held without
 * transfers, that costs more than the money saved buys. The `greedy-1ft` row is flat because
 * transfers repair a weak bench over time — so the effect is real and it is largest exactly where a
 * manager has fewest moves.
 *
 * **This does NOT put the objective back where it was.** `ilp.ts` still emits the XI and captain
 * variables the spec asks for, and the captain's double — absent from the objective entirely before
 * B-023 — is in it. At weight 1.0 the bench term simply contributes nothing, which is the measured
 * answer rather than the original oversight.
 */
export const BENCH_WEIGHT = 0.7;
