/**
 * CLI for `pnpm optimize:bench-sweep` — what a bench place is actually worth (B-023).
 *
 * The optimizer valued all fifteen equally until B-023, which is a quantity FPL never pays out. The
 * fix needs a weight, and `fpl-optimizer` estimates ~0.1 — an estimate, not a fit. **Shipping 0.1
 * unmeasured would trade one arbitrary weight for another**, so this sweeps it and reports what the
 * simulated season says, including when the answer is "the objective cannot tell these apart".
 *
 * Each weight re-picks every predictor's opening fifteen under that weight and walks the full
 * archived season under the real rules — auto-subs, free transfers, sell-on fees — through the SAME
 * simulator `pnpm decision-quality` uses. A sweep with its own harness would be a harness written to
 * flatter the answer.
 *
 * Writes `reports/bench-weight.md`.
 */
import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { Logger } from '@nestjs/common';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { AppModule } from '../app.module';
import { DecisionService } from '../modules/calibration/decision.service';
import { FITTED_PARAMS } from '../modules/projections/fitted';
import { BENCH_WEIGHT } from '../modules/optimizer/policy';

/** 1.0 is the behaviour B-023 replaced — every bench place worth a starting place. */
const WEIGHTS = [0, 0.1, 0.2, 0.35, 0.5, 0.7, 0.85, 1];

async function main(): Promise<void> {
  const log = new Logger('bench-sweep');
  const app = await NestFactory.createApplicationContext(AppModule, {
    // 'log' included: without it the per-weight lines vanish and a silent run reads as a crash.
    logger: ['error', 'warn', 'log'],
  });
  try {
    const service = app.get(DecisionService);
    const rows: {
      weight: number;
      noTransfer: number;
      greedy: number;
      total: number;
      failed?: string;
    }[] = [];

    for (const weight of WEIGHTS) {
      let report;
      try {
        report = await service.evaluate('bench-sweep', FITTED_PARAMS, weight, {
          write: false,
        });
      } catch (err) {
        // A weight that cannot complete a season is a RESULT, not a crash. A bench valued at zero
        // buys four players who may never feature, and a squad that cannot field eleven in some
        // round is exactly the failure a non-zero weight exists to prevent. Recorded and swept past.
        const message = (err as Error).message;
        rows.push({
          weight,
          noTransfer: 0,
          greedy: 0,
          total: 0,
          failed: message,
        });
        log.warn(`weight ${weight}: could not complete a season — ${message}`);
        continue;
      }
      // The MODEL's own squad under each policy — the template row is the crowd's fifteen and does
      // not move with this weight, so including it would dilute the signal with a constant.
      const own = report.seasons.filter((s) => !s.squadLabel);
      const noTransfer = own
        .filter((s) => s.policy === 'no-transfer' && s.predictor === 'model')
        .reduce((t, s) => t + s.totalPoints, 0);
      const greedy = own
        .filter((s) => s.policy === 'greedy-1ft' && s.predictor === 'model')
        .reduce((t, s) => t + s.totalPoints, 0);
      rows.push({ weight, noTransfer, greedy, total: noTransfer + greedy });
      log.log(
        `weight ${weight}: no-transfer ${noTransfer}, greedy-1ft ${greedy}`,
      );
    }

    const ran = rows.filter((r) => !r.failed);
    const best = ran.length
      ? ran.reduce((a, b) => (b.greedy > a.greedy ? b : a))
      : null;
    const spread = ran.length
      ? Math.max(...ran.map((r) => r.greedy)) -
        Math.min(...ran.map((r) => r.greedy))
      : 0;

    const l: string[] = [];
    l.push('# What a bench place is worth');
    l.push('');
    l.push(
      'Generated by `pnpm optimize:bench-sweep`. Each weight re-picks the opening fifteen under that ' +
        'weight and walks the whole archived season under the real rules, through the same simulator ' +
        '`pnpm decision-quality` uses.',
    );
    l.push('');
    l.push(
      '**1.0 is the behaviour B-023 replaced** — every bench place worth exactly a starting place, ' +
        'which is a quantity FPL never pays out.',
    );
    l.push('');
    l.push('| bench weight | no-transfer | greedy-1ft |');
    l.push('|---:|---:|---:|');
    for (const r of rows) {
      const mark = r.weight === BENCH_WEIGHT ? ' ← shipped' : '';
      l.push(
        r.failed
          ? `| ${r.weight}${mark} | — | — |  *could not complete a season: ${r.failed}* |`
          : `| ${r.weight}${mark} | ${r.noTransfer} | ${r.greedy} |`,
      );
    }
    l.push('');
    if (best) {
      l.push(
        `Best under \`greedy-1ft\`: **${best.weight}** at ${best.greedy} points. Spread across the ` +
          `weights that completed a season: **${spread} points** over 38 gameweeks.`,
      );
    }
    const failures = rows.filter((r) => r.failed);
    if (failures.length > 0) {
      l.push('');
      l.push(
        `**${failures.length} weight(s) could not complete a season at all**, which is a result in ` +
          'its own right. A bench valued at or near zero buys four players the objective has no ' +
          'reason to care about, and a squad that cannot field eleven in some round is precisely ' +
          'the failure a non-zero weight exists to prevent.',
      );
    }
    l.push('');
    l.push(
      '**Read the spread before the winner.** One simulated season is one draw, and a difference of ' +
        'a few points over 38 gameweeks is not a measurement — it is the same noise that made D-023 ' +
        'a rule. If the column above is flat, the honest statement is that the season simulator ' +
        'cannot tell these weights apart, and the shipped value is a POLICY constant carrying the ' +
        'structural argument (a bench place is worth less than a starting place) rather than a ' +
        'fitted one.',
    );
    l.push('');
    l.push(
      'What the sweep CAN establish is the direction: whether the old behaviour, weight 1.0, is ' +
        'worse than a discounted bench at all. That is the claim B-023 makes, and it is the one to ' +
        'read off the bottom row.',
    );
    l.push('');

    await mkdir('reports', { recursive: true });
    const path = join('reports', 'bench-weight.md');
    await writeFile(path, l.join('\n'), 'utf8');
    log.log(`report: ${path}`);
    await app.close();
    process.exit(0);
  } catch (err) {
    log.error((err as Error).stack ?? (err as Error).message);
    await app.close();
    process.exit(1);
  }
}

void main();
