/**
 * CLI for `pnpm ingest:availability`: recover deadline-time availability flags for past seasons
 * from Wayback Machine captures of `bootstrap-static` into `archive_availability_snapshot`
 * (B-015, plan 024), and write the per-round coverage report the fit's exclusion rule reads.
 *
 * Compiled-run pattern like `import:archive`. Network + Postgres; safe to re-run — each season is
 * replaced wholesale, and immutable captures are cached under `.archive-cache/wayback/`.
 *
 * `pnpm ingest:availability 2025-26` ingests one season.
 */
import 'dotenv/config';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { NestFactory } from '@nestjs/core';
import { Logger } from '@nestjs/common';
import { AppModule } from '../app.module';
import { ARCHIVE_SEASONS } from '../modules/archive/archive.mappers';
import {
  SeasonIngestSummary,
  WaybackAvailabilityService,
} from '../modules/archive/wayback-availability.service';

/** Rounds whose nearest capture is staler than this are excluded from the fit (plan 024). */
const GAP_EXCLUSION_HOURS = 72;

function coverageReport(summaries: SeasonIngestSummary[]): string {
  const lines: string[] = [
    '# Availability coverage — Wayback deadline snapshots',
    '',
    'Generated by `pnpm ingest:availability` (B-015, plan 024). Per past round: the last',
    '`bootstrap-static` capture strictly before the deadline, its staleness, and the size of the',
    `flagged population. Rounds with a gap over ${GAP_EXCLUSION_HOURS} h are marked excluded — the`,
    'fit must not read them, and the count of exclusions is part of any result quoted from this data.',
    '',
  ];
  for (const s of summaries) {
    const excluded = s.coverage.filter(
      (c) => c.gapHours !== null && c.gapHours > GAP_EXCLUSION_HOURS,
    );
    lines.push(
      `## ${s.season}`,
      '',
      `${s.roundsCaptured}/${s.rounds} rounds captured, ${s.rowsWritten} rows, ` +
        `max gap ${s.maxGapHours.toFixed(1)} h, ` +
        `${excluded.length} round(s) excluded at ${GAP_EXCLUSION_HOURS} h` +
        (s.roundsMissing.length > 0
          ? `, missing entirely: GW${s.roundsMissing.join(', GW')}`
          : ''),
      '',
      '| round | deadline (UTC) | capture (UTC) | gap h | players | flagged | doubtful band | fit |',
      '|---|---|---|---|---|---|---|---|',
    );
    for (const c of s.coverage) {
      const fit =
        c.snapshotAt === null
          ? 'missing'
          : (c.gapHours ?? 0) > GAP_EXCLUSION_HOURS
            ? 'EXCLUDED'
            : 'in';
      lines.push(
        `| ${c.round} | ${c.deadlineAt.toISOString().slice(0, 16)} | ` +
          `${c.snapshotAt ? c.snapshotAt.toISOString().slice(0, 16) : '—'} | ` +
          `${c.gapHours === null ? '—' : c.gapHours.toFixed(1)} | ` +
          `${c.players} | ${c.flagged} | ${c.doubtful} | ${fit} |`,
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}

async function main(): Promise<void> {
  const log = new Logger('ingest-availability');
  const requested = process.argv.slice(2).filter((a) => !a.startsWith('-'));
  const seasons = requested.length > 0 ? requested : [...ARCHIVE_SEASONS];

  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: ['error', 'warn', 'log'],
  });
  try {
    const summaries = await app.get(WaybackAvailabilityService).ingestAll(seasons);

    const reportPath = join(process.cwd(), 'reports', 'availability-coverage.md');
    await writeFile(reportPath, coverageReport(summaries));
    log.log(`coverage report written to ${reportPath}`);

    for (const s of summaries) {
      log.log(
        `${s.season}: ${s.roundsCaptured}/${s.rounds} rounds, ${s.rowsWritten} rows, ` +
          `max gap ${s.maxGapHours.toFixed(1)}h`,
      );
    }
    await app.close();
    process.exit(0);
  } catch (err) {
    log.error((err as Error).message);
    await app.close();
    process.exit(1);
  }
}

void main();
