/**
 * CLI for `pnpm report:setpiece` — the set-piece prior, measured before anything is built on it.
 *
 * The guide (§2.3) says this single table swings expected points more than most model features, and
 * this project captures `penaltiesOrder`, `directFreekicksOrder` and `cornersOrder` at every deadline
 * and reads them nowhere. B-017 asked for the effect to be measured on the archive first.
 *
 * **The backlog said the archive carries these fields per season, and it does not.** Checked
 * 2026-08-27: the per-gameweek CSVs have no order columns at all. What the archive does carry is
 * `players_raw.csv` per season, which is a season-end bootstrap dump with `code`, `penalties_order`,
 * `direct_freekicks_order` and `corners_and_indirect_freekicks_order`.
 *
 * **So the join is season-level, and the value is a season-END one.** A player who took the penalties
 * in January reads as the taker for the whole season, including the four months he was not. That
 * biases the measured effect UPWARD — the job tends to go to whoever is scoring — and it is the
 * reason this report exists as a measurement and not as a model change. A number that flatters
 * itself is worth having only if it says so.
 *
 * Writes `reports/set-piece-prior.md`. Fetches three CSVs and reads Postgres; writes no table.
 */
import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { Logger } from '@nestjs/common';
import { AppModule } from '../app.module';
import { PrismaService } from '../infra/prisma/prisma.service';
import { parseCsv } from '../modules/archive/csv';
import { ARCHIVE_SEASONS } from '../modules/archive/archive.mappers';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const BASE =
  'https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data';

interface SetPiece {
  penalties: number | null;
  freekicks: number | null;
  corners: number | null;
}

/** Order columns are blank for "not on the list", which is not the same as being last in a queue. */
function order(cell: string | undefined): number | null {
  if (cell === undefined || cell.trim() === '') return null;
  const n = Number(cell);
  return Number.isFinite(n) && n > 0 ? n : null;
}

async function setPieceFor(season: string): Promise<Map<number, SetPiece>> {
  const res = await fetch(`${BASE}/${season}/players_raw.csv`, {
    headers: { 'User-Agent': process.env.FPL_USER_AGENT ?? 'fpl-manager/0.1' },
  });
  if (!res.ok) throw new Error(`${season}/players_raw.csv: HTTP ${res.status}`);
  const rows = parseCsv(await res.text());
  const header = rows[0];
  const at = (name: string) => header.indexOf(name);
  const iCode = at('code');
  const iPen = at('penalties_order');
  const iFk = at('direct_freekicks_order');
  const iCorner = at('corners_and_indirect_freekicks_order');
  if (iCode < 0 || iPen < 0) {
    throw new Error(
      `${season}/players_raw.csv has no code/penalties_order column — the archive's shape changed`,
    );
  }

  const out = new Map<number, SetPiece>();
  for (const r of rows.slice(1)) {
    const code = Number(r[iCode]);
    if (!Number.isFinite(code)) continue;
    out.set(code, {
      penalties: order(r[iPen]),
      freekicks: iFk >= 0 ? order(r[iFk]) : null,
      corners: iCorner >= 0 ? order(r[iCorner]) : null,
    });
  }
  return out;
}

interface Bucket {
  label: string;
  players: number;
  minutes: number;
  goals: number;
  assists: number;
}

const per90 = (total: number, minutes: number) =>
  minutes > 0 ? (total / minutes) * 90 : 0;

async function main(): Promise<void> {
  const log = new Logger('report:setpiece');
  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: ['error', 'warn', 'log'],
  });
  try {
    const prisma = app.get(PrismaService);
    const lines: string[] = [];
    lines.push('# The set-piece prior, measured');
    lines.push('');
    lines.push(
      'Generated by `pnpm report:setpiece`. Season-level join of `players_raw.csv` ' +
        '(`penalties_order`, `direct_freekicks_order`, `corners_and_indirect_freekicks_order`) onto ' +
        'the per-gameweek archive, by `code`.',
    );
    lines.push('');
    lines.push(
      '**Read the caveat before the numbers.** The order is a season-END value. A player who took ' +
        'the job in January reads as the taker for the whole season, including the four months he ' +
        'was not — and the job tends to go to whoever is already scoring. That biases every effect ' +
        'below **upward**. This is a measurement, not a model feature, and the gap between those two ' +
        'is exactly this paragraph.',
    );
    lines.push('');

    for (const season of ARCHIVE_SEASONS) {
      const sp = await setPieceFor(season);
      const totals = await prisma.archivePlayerGameweek.groupBy({
        by: ['playerCode', 'position'],
        where: { season },
        _sum: { minutes: true, goalsScored: true, assists: true },
      });

      const buckets = new Map<string, Bucket>();
      const add = (label: string, row: (typeof totals)[number]) => {
        const b = buckets.get(label) ?? {
          label,
          players: 0,
          minutes: 0,
          goals: 0,
          assists: 0,
        };
        b.players += 1;
        b.minutes += row._sum.minutes ?? 0;
        b.goals += row._sum.goalsScored ?? 0;
        b.assists += row._sum.assists ?? 0;
        buckets.set(label, b);
      };

      let matched = 0;
      for (const row of totals) {
        // Keepers are excluded: they are on nobody's set-piece list and would dilute every bucket
        // with 0 goals per 90, making "not on the list" look worse than it is.
        if (row.position === 'GKP') continue;
        if ((row._sum.minutes ?? 0) < 450) continue; // a season's worth of a squad player
        const entry = sp.get(row.playerCode);
        if (!entry) continue;
        matched += 1;
        add(
          entry.penalties === 1
            ? 'penalties: first choice'
            : entry.penalties !== null
              ? 'penalties: on the list, not first'
              : 'penalties: not on the list',
          row,
        );
        if (entry.corners === 1) add('corners: first choice', row);
        if (entry.freekicks === 1) add('direct free kicks: first choice', row);
      }

      lines.push(`## ${season}`);
      lines.push('');
      lines.push(
        `${matched.toLocaleString()} outfield players with 450+ minutes matched to a set-piece row.`,
      );
      lines.push('');
      lines.push(
        '| bucket | players | minutes | goals/90 | assists/90 | returns/90 |',
      );
      lines.push('|---|---:|---:|---:|---:|---:|');
      const ordered = [
        'penalties: first choice',
        'penalties: on the list, not first',
        'penalties: not on the list',
        'direct free kicks: first choice',
        'corners: first choice',
      ];
      for (const label of ordered) {
        const b = buckets.get(label);
        if (!b) continue;
        lines.push(
          `| ${b.label} | ${b.players} | ${b.minutes.toLocaleString()} | ` +
            `${per90(b.goals, b.minutes).toFixed(3)} | ${per90(b.assists, b.minutes).toFixed(3)} | ` +
            `${per90(b.goals + b.assists, b.minutes).toFixed(3)} |`,
        );
      }
      lines.push('');

      const first = buckets.get('penalties: first choice');
      const none = buckets.get('penalties: not on the list');
      if (first && none) {
        const lift =
          per90(first.goals, first.minutes) - per90(none.goals, none.minutes);
        lines.push(
          `**The penalty lift for ${season}: ${lift.toFixed(3)} goals per 90**, first-choice taker ` +
            `against not on the list. The guide's rule of thumb is "roughly a tenth of a goal per ` +
            `game before anything else is known about him".`,
        );
        lines.push('');
        log.log(
          `${season}: penalty lift ${lift.toFixed(3)} goals/90 ` +
            `(${first.players} takers vs ${none.players} non-takers)`,
        );
      }
    }

    lines.push('---');
    lines.push('');
    lines.push(
      '**What this does NOT establish.** That the lift is causal, or that it survives the ' +
        'season-end bias described at the top, or that it adds anything the model does not already ' +
        'get from a player’s own lagged xG — which for a penalty taker already includes his ' +
        'penalties. That last one is the important one: the model reads xG per 90, and a penalty is ' +
        'about 0.76 xG. Adding a set-piece term on top would double-count unless it is fitted ' +
        'against the residual, and no such fit is done here.',
    );
    lines.push('');

    await mkdir('reports', { recursive: true });
    const path = join('reports', 'set-piece-prior.md');
    await writeFile(path, lines.join('\n'), 'utf8');
    log.log(`report: ${path}`);
    await app.close();
    process.exit(0);
  } catch (err) {
    log.error((err as Error).message);
    await app.close();
    process.exit(1);
  }
}

void main();
