"""Does a gradient-boosted model get better with ten seasons instead of three? (plan 027 task 7)

VALIDATION ONLY, and that is the whole design. The archive holdout is spent — `fit.py` records that
its next TEST reading is the last, and D-034 retired 2025-26 as a season anything may be selected on
— so this script reads no TEST row, emits no model, and writes nothing into
`src/modules/projections/v4`. It answers one question at the only place a question may still be
asked: is validation RMSE lower when the same grid trains on every season the archive holds?

Run the narrow export first (`pnpm export:features`), then the wide one
(`pnpm export:features --all-seasons`), passing `--label` each time. Both readings land in
`reports/v4-wide-validation.md`.

The split is `fit.py`'s, reused rather than reinvented: VALIDATE is 2024-25 from round 20, and the
training side is everything before it — which is what differs between the two exports.
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb

ROOT = Path(__file__).resolve().parents[2]
DATASETS = ROOT / "reports" / "datasets"
POSITIONS = ["GKP", "DEF", "MID", "FWD"]
SEED = 20260827
VALIDATE_FROM_ROUND = 20
VALIDATE_SEASON = "2024-25"
TEST_SEASON = "2025-26"

# fit.py's grid, trimmed to the depths and rates that won there. A wider grid on one half-season of
# validation rounds finds a winner whether or not one exists — the failure D-023 is about.
GRID = [
    {"max_depth": d, "learning_rate": lr, "min_child_weight": mcw, "gamma": g}
    for d in (3, 4)
    for lr in (0.03, 0.06)
    for mcw in (20, 100)
    for g in (0.0, 2.0)
]
FIXED = {
    "n_estimators": 2000,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "objective": "reg:squarederror",
    "eval_metric": "rmse",
    "early_stopping_rounds": 50,
    "random_state": SEED,
    "n_jobs": -1,
}


def main(label: str) -> None:
    manifest = json.loads((DATASETS / "manifest.json").read_text())
    cols = manifest["featureNames"]
    lines = []
    seasons = ", ".join(sorted(manifest["seasons"]))
    lines.append(
        f"## {label} — {manifest['totalRows']:,} rows over {len(manifest['seasons'])} seasons "
        f"({seasons})"
    )
    lines.append("")
    lines.append("| position | train rows | validate rows | best val RMSE | chosen |")
    lines.append("|---|---:|---:|---:|---|")

    for position in POSITIONS:
        df = pd.read_csv(DATASETS / f"v4-{position}.csv")
        missing = [c for c in cols if c not in df.columns]
        assert not missing, f"manifest features absent from CSV: {missing}"
        # Never a TEST row, in training or in scoring. The assertion is here rather than in a comment
        # because this script exists precisely to avoid spending what is already spent.
        train = df[
            (df.season < VALIDATE_SEASON)
            | ((df.season == VALIDATE_SEASON) & (df["round"] < VALIDATE_FROM_ROUND))
        ]
        val = df[(df.season == VALIDATE_SEASON) & (df["round"] >= VALIDATE_FROM_ROUND)]
        assert (train.season != TEST_SEASON).all() and (val.season != TEST_SEASON).all()
        assert len(train) and len(val)

        # The residual target, which is the architecture the register left standing (B-037).
        ytr = train["totalPoints"] - train["v3epBase"]
        yva = val["totalPoints"] - val["v3epBase"]
        best_rmse, best_params = float("inf"), None
        for params in GRID:
            model = xgb.XGBRegressor(**FIXED, **params)
            model.fit(train[cols], ytr, eval_set=[(val[cols], yva)], verbose=False)
            rmse = float(np.sqrt(np.mean((model.predict(val[cols]) - yva) ** 2)))
            if rmse < best_rmse:
                best_rmse, best_params = rmse, params
        lines.append(
            f"| {position} | {len(train):,} | {len(val):,} | {best_rmse:.4f} | "
            f"depth {best_params['max_depth']}, lr {best_params['learning_rate']}, "
            f"mcw {best_params['min_child_weight']}, gamma {best_params['gamma']} |"
        )
        print(f"{position}: train {len(train)}, val {len(val)}, best val RMSE {best_rmse:.4f}")

    out = ROOT / "reports" / "v4-wide-validation.md"
    header = (
        "# v4 on ten seasons — validation only\n\n"
        "Does a gradient-boosted model get better with more seasons where the decomposed model does "
        "not? Measured at the only place a question may still be asked of this archive: VALIDATE, "
        "2024-25 from round 20. No TEST row is read, no model is emitted, nothing under "
        "`src/modules/projections/v4` is touched. Generated by `tools/fit-v4/wide-validation.py`.\n"
    )
    existing = out.read_text() if out.exists() else header
    if not existing.startswith("#"):
        existing = header
    out.write_text(existing.rstrip() + "\n\n" + "\n".join(lines) + "\n")
    print(f"report: {out}")


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--label", required=True)
    main(ap.parse_args().label)
