import { StrengthParams } from './strength';

/**
 * Every number the projection model used to guess.
 *
 * v1's constants were first estimates written into `model.ts` and `minutes.ts` — `0.7` for the defcon
 * ramp, `0.15` per FDR step, `85` starter minutes, a `0.6` bonus coefficient. None was fitted to
 * anything, because until B-007 Phase 2b there was one gameweek of data to fit to.
 *
 * They live here rather than in a database table for the same reason the reconstructed scoring tables
 * do: **a fitted number has to be reviewable in a diff.** A constant that changes silently between
 * runs is indistinguishable from a bug, and `provenance` below is what makes a later session able to
 * tell whether a value was measured or typed.
 *
 * Regenerate with `pnpm fit:model`, which prints this file's contents and the objective it minimised.
 */

export interface MinutesParams {
  /** P(start) given a lagged start rate — a logistic on it, fitted rather than assumed to be identity */
  startIntercept: number;
  startSlope: number;
  /**
   * P(appearing at all | not starting), as ONE league-wide number.
   *
   * Kept as the fallback the sub curve collapses to, and as the number the report quotes for the
   * population. It is no longer what the model multiplies by: B-013 measured that constant as the
   * model's worst-calibrated shape, because it pays a never-used fringe player and a first substitute
   * the same 15.4%.
   */
  subAppearanceRate: number;
  /**
   * The sub curve — `P(appear | did not start)` as a logistic on the logit of the player's OWN lagged
   * rate, fitted the same way `startIntercept`/`startSlope` are (B-019).
   *
   * `subSlope: 0` reduces this exactly to the old constant behaviour with
   * `subIntercept = logit(subAppearanceRate)`, which is how the unfitted baseline states it.
   */
  subIntercept: number;
  subSlope: number;
  /** P(playing 60+ | started) — a starter is not a certainty to see the hour */
  sixtyGivenStart: number;
  /** P(playing 60+ | came off the bench) */
  sixtyGivenSub: number;
  /** E[minutes | started] and E[minutes | sub], for the expected-minutes report only */
  minutesGivenStart: number;
  minutesGivenSub: number;
}

export interface AttackParams {
  /** how much of a fixture's goal-rate advantage carries into an individual's xG — 1 = fully */
  xgFixtureElasticity: number;
  xaFixtureElasticity: number;
  /** finishing conversion: realised goals per unit of xG, ~1 if xG is unbiased */
  goalsPerXg: number;
  assistsPerXa: number;
}

export interface DefconParams {
  /** overdispersion of the qualifying-action count relative to Poisson; 1 is pure Poisson */
  dispersion: number;
  /** how a player's per-90 rate scales with minutes actually played */
  ratePer90ToMatch: number;
}

export interface BonusParams {
  /** expected bonus points per BPS above the match's typical bonus line */
  bonusPerBps: number;
  bpsIntercept: number;
  /** cap, since only three players in a match receive bonus at all */
  maxBonus: number;
}

export interface FittedParams {
  strength: StrengthParams;
  minutes: MinutesParams;
  attack: AttackParams;
  defcon: DefconParams;
  bonus: BonusParams;
  provenance: {
    fittedOn: string[];
    rows: number;
    date: string;
    objective: string;
    heldOut: string;
    notes: string[];
  };
}

/**
 * The starting point: v1's guesses, restated in the v2 shape.
 *
 * This is not a fit and does not pretend to be. It exists so the harness has something to score before
 * anything is fitted — the baseline the fitted parameters have to beat, on the same held-out rows. A
 * v2 that cannot beat these is a v2 that changed the code and nothing else.
 */
export const UNFITTED_PARAMS: FittedParams = {
  strength: {
    homeAdvantage: 1.15,
    confidenceMatches: 4,
    leagueGoalsPerTeamMatch: 1.4,
  },
  minutes: {
    startIntercept: 0,
    startSlope: 1,
    subAppearanceRate: 0.35,
    // slope 0 => the curve is flat at the constant, which is exactly what v1 did.
    subIntercept: Math.log(0.35 / 0.65),
    subSlope: 0,
    sixtyGivenStart: 0.85,
    sixtyGivenSub: 0.05,
    minutesGivenStart: 85,
    minutesGivenSub: 25,
  },
  attack: {
    xgFixtureElasticity: 1,
    xaFixtureElasticity: 1,
    goalsPerXg: 1,
    assistsPerXa: 1,
  },
  defcon: { dispersion: 1, ratePer90ToMatch: 1 },
  bonus: { bonusPerBps: 0, bpsIntercept: 0, maxBonus: 3 },
  provenance: {
    fittedOn: [],
    rows: 0,
    date: '—',
    objective: 'none — these are v1 guesses restated, not a fit',
    heldOut: '—',
    notes: [
      'The baseline the fitted parameters must beat on held-out rows.',
      'subAppearanceRate 0.35, minutes 85/25 and the 1.15 home advantage are v1 values.',
    ],
  },
};

/**
 * The fitted parameters, regenerated by `pnpm fit:model`.
 *
 * Replaced wholesale from that script's output — edit the fit, not this object.
 *
 * **What changed from the guesses, and what it means:**
 *
 * | knob | v1 guess | fitted | what the data said |
 * |---|---|---|---|
 * | `subAppearanceRate` | 0.35 | 0.154 | a benched player appears less than half as often as assumed |
 * | `sixtyGivenStart` | 0.85 | 0.934 | a starter sees the hour more often than assumed |
 * | `sixtyGivenSub` | 0.05 | 0.013 | a substitute almost never does |
 * | `minutesGivenSub` | 25 | 18.2 | substitutes get less than assumed |
 * | `startSlope` | 1 (identity) | 0.485 | **the opposite of the expected direction** |
 * | `homeAdvantage` | 1.15 | 1.119 | close to the guess |
 * | `assistsPerXa` | 1 | 1.395 | assists land well above expected assists |
 * | `defcon.dispersion` | 1 (Poisson) | 1.5 | defensive actions cluster, as suspected |
 * | `xgFixtureElasticity` | 1 | **0** | see below |
 * | `subSlope` | — (a flat 0.154) | **1.384** | the sub term is a curve now, see below |
 *
 * Three results worth reading before trusting anything built on this:
 *
 * - **`startSlope` 0.485, not 1.** v1 used a player's lagged start rate directly as P(start). The
 *   fitted curve is much flatter: a player who started every recent match is *not* a certainty, and
 *   one who started none is not hopeless. The first attempt at this fit returned a slope of 7.3e8 —
 *   complete separation running away to a step function — which is why the fit now carries a ridge
 *   penalty and a sanity bound.
 * - **The substitute-appearance term is a curve now, and it was the model's worst shape.** B-013
 *   scored every term on its own and `P(any appearance)` carried a Brier reliability of 0.0121
 *   against a mean of 0.0012 for every other binary: one global `subAppearanceRate` paid a
 *   never-used fringe player and a first substitute the same 15.4%. `subSlope` **1.384** is steeper
 *   than 1, the opposite direction to `startSlope` — the lagged sub rate is heavily smoothed toward
 *   the population prior before the model sees it, so the fit un-shrinks it.
 * - **Both fixture elasticities fitted to 0**, and `confidenceMatches` ran to the top of its grid.
 *   Held-out RMSE says the fixture-strength signal does not improve a SINGLE-GAMEWEEK points
 *   prediction: player-level variance swamps it. That is a real finding rather than a broken input —
 *   the same strength still drives clean sheets and goals conceded through λ_against, where it does
 *   pay. It should not be read as "fixtures do not matter" over a multi-gameweek horizon, which this
 *   backtest does not measure.
 */
export const FITTED_PARAMS: FittedParams = {
  strength: {
    homeAdvantage: 1.1186408380003194,
    confidenceMatches: 96,
    leagueGoalsPerTeamMatch: 1.5486291739894333,
  },
  minutes: {
    startIntercept: -0.18790070079541765,
    startSlope: 0.4849268629262438,
    subAppearanceRate: 0.15435726210350584,
    subIntercept: 0.5746772470150242,
    subSlope: 1.3841301233905476,
    sixtyGivenStart: 0.9339351334078926,
    sixtyGivenSub: 0.013411204845338524,
    minutesGivenStart: 82.83320019172392,
    minutesGivenSub: 18.151633138654553,
  },
  attack: {
    xgFixtureElasticity: 0,
    xaFixtureElasticity: 0,
    goalsPerXg: 0.9890259541292118,
    assistsPerXa: 1.3951956123013418,
  },
  defcon: { dispersion: 1.5, ratePer90ToMatch: 0.9 },
  bonus: {
    bonusPerBps: 0.04173248388494878,
    bpsIntercept: -0.2839231900427406,
    maxBonus: 3,
  },
  provenance: {
    fittedOn: ['2023-24', '2024-25'],
    rows: 42468,
    date: '2026-08-27',
    objective:
      'frequencies measured directly; shape parameters by RMSE on held-out 2024-25 rounds 20+ ' +
      '(14,540 rows). RMSE deliberately, not MAE: MAE is minimised by the conditional median and ' +
      'this corpus is mostly near-zero rows, so an MAE search shrank every parameter toward ' +
      'predicting nobody scores.',
    heldOut:
      '2025-26 rounds 13-38 entirely; rounds 1-12 (8,818 rows) are read by the defensive-contribution ' +
      'parameters and by nothing else. Live 2026/27 untouched.',
    notes: [
      'The defensive-contribution parameters are the ONE exception to the holdout: that category exists only in 2025-26, so dispersion is fitted on rounds 1-12 and ratePer90ToMatch chosen on 13-19. Those rows are passed separately and no other parameter reads them — an earlier version folded them into the training set, where the frequency measurements iterated them too, so a quarter of the test season silently informed the whole fit while this note claimed otherwise.',
      'The availability multiplier is NOT fitted: the archive carries no per-gameweek status or chance_of_playing. It waits on player_deadline_snapshot (B-007 Phase 2) accumulating live gameweeks.',
      'strength.confidenceMatches reached the top of its search grid — the optimum is at or beyond 96, meaning held-out RMSE keeps improving as team strength is shrunk toward the league average.',
      'Both fixture elasticities fitted to 0 on single-gameweek RMSE. Team strength still drives clean sheets and goals conceded through lambda-against.',
      'xaFixtureElasticity: the grid was FLAT — every value from 1.0 to 2.0 scored 1.9497 and the whole grid spanned 0.0007 RMSE. A grid search returns a winner whether or not its objective can tell the candidates apart, so the search now takes the NULL candidate (no effect) when the spread is under 0.001, and says so. Without that rule this parameter would have shipped as 1.5 — a claim that the fixture moves assists by half again, on evidence of seven ten-thousandths of a point.',
      'subIntercept/subSlope replace the scalar subAppearanceRate (B-019). Fitted on non-start rows only — the population the term is asked about at prediction time. subAppearanceRate is kept as the population rate the report quotes and as the flat-curve fallback.',
    ],
  },
};
