import { StrengthParams } from './strength';

/**
 * Every number the projection model used to guess.
 *
 * v1's constants were first estimates written into `model.ts` and `minutes.ts` — `0.7` for the defcon
 * ramp, `0.15` per FDR step, `85` starter minutes, a `0.6` bonus coefficient. None was fitted to
 * anything, because until B-007 Phase 2b there was one gameweek of data to fit to.
 *
 * They live here rather than in a database table for the same reason the reconstructed scoring tables
 * do: **a fitted number has to be reviewable in a diff.** A constant that changes silently between
 * runs is indistinguishable from a bug, and `provenance` below is what makes a later session able to
 * tell whether a value was measured or typed.
 *
 * Regenerate with `pnpm fit:model`, which prints this file's contents and the objective it minimised.
 */

export interface MinutesParams {
  /** P(start) given a lagged start rate — a logistic on it, fitted rather than assumed to be identity */
  startIntercept: number;
  startSlope: number;
  /** P(appearing at all | not starting) */
  subAppearanceRate: number;
  /** P(playing 60+ | started) — a starter is not a certainty to see the hour */
  sixtyGivenStart: number;
  /** P(playing 60+ | came off the bench) */
  sixtyGivenSub: number;
  /** E[minutes | started] and E[minutes | sub], for the expected-minutes report only */
  minutesGivenStart: number;
  minutesGivenSub: number;
}

export interface AttackParams {
  /** how much of a fixture's goal-rate advantage carries into an individual's xG — 1 = fully */
  xgFixtureElasticity: number;
  xaFixtureElasticity: number;
  /** finishing conversion: realised goals per unit of xG, ~1 if xG is unbiased */
  goalsPerXg: number;
  assistsPerXa: number;
}

export interface DefconParams {
  /** overdispersion of the qualifying-action count relative to Poisson; 1 is pure Poisson */
  dispersion: number;
  /** how a player's per-90 rate scales with minutes actually played */
  ratePer90ToMatch: number;
}

export interface BonusParams {
  /** expected bonus points per BPS above the match's typical bonus line */
  bonusPerBps: number;
  bpsIntercept: number;
  /** cap, since only three players in a match receive bonus at all */
  maxBonus: number;
}

export interface FittedParams {
  strength: StrengthParams;
  minutes: MinutesParams;
  attack: AttackParams;
  defcon: DefconParams;
  bonus: BonusParams;
  provenance: {
    fittedOn: string[];
    rows: number;
    date: string;
    objective: string;
    heldOut: string;
    notes: string[];
  };
}

/**
 * The starting point: v1's guesses, restated in the v2 shape.
 *
 * This is not a fit and does not pretend to be. It exists so the harness has something to score before
 * anything is fitted — the baseline the fitted parameters have to beat, on the same held-out rows. A
 * v2 that cannot beat these is a v2 that changed the code and nothing else.
 */
export const UNFITTED_PARAMS: FittedParams = {
  strength: {
    homeAdvantage: 1.15,
    confidenceMatches: 4,
    leagueGoalsPerTeamMatch: 1.4,
  },
  minutes: {
    startIntercept: 0,
    startSlope: 1,
    subAppearanceRate: 0.35,
    sixtyGivenStart: 0.85,
    sixtyGivenSub: 0.05,
    minutesGivenStart: 85,
    minutesGivenSub: 25,
  },
  attack: {
    xgFixtureElasticity: 1,
    xaFixtureElasticity: 1,
    goalsPerXg: 1,
    assistsPerXa: 1,
  },
  defcon: { dispersion: 1, ratePer90ToMatch: 1 },
  bonus: { bonusPerBps: 0, bpsIntercept: 0, maxBonus: 3 },
  provenance: {
    fittedOn: [],
    rows: 0,
    date: '—',
    objective: 'none — these are v1 guesses restated, not a fit',
    heldOut: '—',
    notes: [
      'The baseline the fitted parameters must beat on held-out rows.',
      'subAppearanceRate 0.35, minutes 85/25 and the 1.15 home advantage are v1 values.',
    ],
  },
};

/**
 * The fitted parameters, regenerated by `pnpm fit:model`.
 *
 * Replaced wholesale from that script's output — edit the fit, not this object.
 *
 * **What changed from the guesses, and what it means:**
 *
 * | knob | v1 guess | fitted | what the data said |
 * |---|---|---|---|
 * | `subAppearanceRate` | 0.35 | 0.157 | a benched player appears less than half as often as assumed |
 * | `sixtyGivenStart` | 0.85 | 0.932 | a starter sees the hour more often than assumed |
 * | `sixtyGivenSub` | 0.05 | 0.015 | a substitute almost never does |
 * | `minutesGivenSub` | 25 | 18.3 | substitutes get less than assumed |
 * | `startSlope` | 1 (identity) | 0.467 | **the opposite of the expected direction** |
 * | `homeAdvantage` | 1.15 | 1.123 | close to the guess |
 * | `assistsPerXa` | 1 | 1.415 | assists land well above expected assists |
 * | `defcon.dispersion` | 1 (Poisson) | 1.5 | defensive actions cluster, as suspected |
 * | `xgFixtureElasticity` | 1 | **0** | see below |
 *
 * Two results worth reading before trusting anything built on this:
 *
 * - **`startSlope` 0.467, not 1.** v1 used a player's lagged start rate directly as P(start). The
 *   fitted curve is much flatter: a player who started every recent match is *not* a certainty, and
 *   one who started none is not hopeless. The first attempt at this fit returned a slope of 7.3e8 —
 *   complete separation running away to a step function — which is why the fit now carries a ridge
 *   penalty and a sanity bound.
 * - **Both fixture elasticities fitted to 0**, and `confidenceMatches` ran to the top of its grid.
 *   Held-out RMSE says the fixture-strength signal does not improve a SINGLE-GAMEWEEK points
 *   prediction: player-level variance swamps it. That is a real finding rather than a broken input —
 *   the same strength still drives clean sheets and goals conceded through λ_against, where it does
 *   pay. It should not be read as "fixtures do not matter" over a multi-gameweek horizon, which this
 *   backtest does not measure.
 */
export const FITTED_PARAMS: FittedParams = {
  strength: {
    homeAdvantage: 1.1233471839072462,
    confidenceMatches: 96,
    leagueGoalsPerTeamMatch: 1.5127213352684714,
  },
  minutes: {
    startIntercept: -0.2022931365788607,
    startSlope: 0.46737973110430747,
    subAppearanceRate: 0.15655447298494243,
    sixtyGivenStart: 0.932378941812904,
    sixtyGivenSub: 0.014674681753889675,
    minutesGivenStart: 82.68637023354005,
    minutesGivenSub: 18.337871287128714,
  },
  attack: {
    xgFixtureElasticity: 0,
    xaFixtureElasticity: 0,
    goalsPerXg: 0.9877526348865678,
    assistsPerXa: 1.4152728373573016,
  },
  defcon: { dispersion: 1.5, ratePer90ToMatch: 0.9 },
  bonus: {
    bonusPerBps: 0.04146475197005556,
    bpsIntercept: -0.2790571016939038,
    maxBonus: 3,
  },
  provenance: {
    fittedOn: ['2023-24', '2024-25'],
    rows: 51286,
    date: '2026-08-26',
    objective:
      'frequencies measured directly; shape parameters by RMSE on held-out 2024-25 rounds 20+ ' +
      '(14,540 rows). RMSE deliberately, not MAE: MAE is minimised by the conditional median and ' +
      'this corpus is mostly near-zero rows, so an MAE search shrank every parameter toward ' +
      'predicting nobody scores.',
    heldOut: '2025-26 (whole season, 29,747 rows), live 2026/27 (untouched)',
    notes: [
      'The defensive-contribution term is NOT held out across seasons — the category exists only in 2025-26. It is fitted on rounds 1-12 of that season and its shape parameter chosen on rounds 13-19, leaving 20-38 unused by it.',
      'The availability multiplier is NOT fitted: the archive carries no per-gameweek status or chance_of_playing. It waits on player_deadline_snapshot (B-007 Phase 2) accumulating live gameweeks.',
      'strength.confidenceMatches reached the top of its search grid — the optimum is at or beyond 96, meaning held-out RMSE keeps improving as team strength is shrunk toward the league average.',
      'Both fixture elasticities fitted to 0 on single-gameweek RMSE. Team strength still drives clean sheets and goals conceded through lambda-against.',
    ],
  },
};
